"""Curated corpus — mirrors the MSMARCO-XI row shape exactly.

Each entry is a (query, answer, passages) triple where passages carry a
gold "is_selected" flag, exactly like the dataset rows. Used as the default
demo corpus so the app boots instantly and works offline. Build the real
MSMARCO-XI index with `HHGOA_USE_REAL=1`.
"""
from __future__ import annotations


def _row(query, eng_query, answer, qtype, passages):
    return {
        "query": query,
        "Eng_Query": eng_query,
        "Answer": answer,
        "query_type": qtype,
        "passages": passages,
    }


FALLBACK_CORPUS: list[dict] = [
    # ---- science & space ----
    _row("मेनहट्टन प्रोजेक्ट की सफलता का तात्कालिक प्रभाव क्या था?",
         "what was the immediate impact of the success of the manhattan project?",
         "मेनहट्टन प्रोजेक्ट की सफलता का तात्कालिक प्रभाव द्वितीय विश्व युद्ध का अंत और जापान का आत्मसमर्पण था।",
         "DESCRIPTION",
         [("परमाणु बम के विकास ने जापान के आत्मसमर्पण में तेजी लाई और द्वितीय विश्व युद्ध समाप्त हुआ। हजारों वैज्ञानिकों और इंजीनियरों ने इस परियोजना में एक साथ काम किया।", True),
          ("वैज्ञानिकों के बीच संचार की उपस्थिति ने परियोजना को समय पर पूरा करने में मदद की।", True),
          ("परियोजना के बाद वैज्ञानिक समुदाय में परिणामों पर गहन बहस हुई।", False)]),
    _row("सौरमंडल का सबसे बड़ा ग्रह कौन सा है?",
         "which is the largest planet in the solar system?",
         "सौरमंडल का सबसे बड़ा ग्रह बृहस्पति है।",
         "ENTITY",
         [("बृहस्पति सौरमंडल का सबसे बड़ा ग्रह है, जो अपनी गैसीय बनावट और ग्रेट रेड स्पॉट के लिए जाना जाता है। इसके 95 से अधिक ज्ञात चंद्रमा हैं।", True),
          ("शनि अपने वलयों के लिए प्रसिद्ध है और आकार में दूसरा सबसे बड़ा ग्रह है।", False),
          ("बुध सौरमंडल का सबसे छोटा ग्रह है।", False)]),
    _row("सूर्य का सतही तापमान कितना होता है?",
         "what is the surface temperature of the sun?",
         "सूर्य की सतह का तापमान लगभग 5,500 डिग्री सेल्सियस है।",
         "NUMERIC",
         [("सूर्य की सतह का तापमान लगभग 5,500 °C है, जबकि इसका केंद्र लगभग 15 मिलियन °C पर परमाणु संलयन करता है।", True),
          ("सूर्य से निकलने वाली ऊर्जा परमाणु संलयन से उत्पन्न होती है।", True)]),
    _row("माउंट एवरेस्ट की ऊँचाई कितनी है?",
         "what is the height of mount everest?",
         "माउंट एवरेस्ट की ऊँचाई 8,848.86 मीटर (29,032 फीट) है।",
         "NUMERIC",
         [("माउंट एवरेस्ट विश्व की सबसे ऊँची चोटी है, जिसकी ऊँचाई 8,848.86 मीटर (29,032 फीट) मापी गई है। यह नेपाल और चीन की सीमा पर स्थित है।", True),
          ("एवरेस्ट पर्वतारोहण पहली बार 1953 में एडमंड हिलेरी और तेनजिंग नोर्गे ने किया था।", True)]),
    _row("प्रकाश संश्लेषण क्या है?",
         "what is photosynthesis?",
         "प्रकाश संश्लेषण वह प्रक्रिया है जिसमें पौधे सूर्य के प्रकाश से कार्बन डाइऑक्साइड और पानी का उपयोग करके भोजन बनाते हैं।",
         "DESCRIPTION",
         [("प्रकाश संश्लेषण में पौधे क्लोरोफिल की मदद से सूर्य की ऊर्जा को रासायनिक ऊर्जा में बदलते हैं, कार्बन डाइऑक्साइड और पानी को ग्लूकोज़ और ऑक्सीजन में परिवर्तित करते हैं।", True),
          ("यह प्रक्रिया मुख्य रूप से पत्तियों में स्थित क्लोरोप्लास्ट में होती है।", True)]),
    _row("पानी का रासायनिक सूत्र क्या है?",
         "what is the chemical formula of water?",
         "पानी का रासायनिक सूत्र H2O है।",
         "ENTITY",
         [("पानी का रासायनिक सूत्र H2O है, जिसमें दो हाइड्रोजन परमाणु और एक ऑक्सीजन परमाणु होते हैं।", True),
          ("कार्बन डाइऑक्साइड का रासायनिक सूत्र CO2 है।", False)]),
    _row("ओजोन परत क्यों महत्वपूर्ण है?",
         "why is the ozone layer important?",
         "ओजोन परत सूर्य की हानिकारक पराबैंगनी किरणों से पृथ्वी पर जीवन की रक्षा करती है।",
         "DESCRIPTION",
         [("ओजोन परत समतापमंडल में स्थित है और सूर्य की हानिकारक पराबैंगनी (UV-B) किरणों को अवशोषित कर पृथ्वी पर जीवन की रक्षा करती है।", True),
          ("ओजोन परत के क्षरण के प्रमुख कारण क्लोरोफ्लोरोकार्बन (CFC) गैसें थीं।", True)]),
    _row("हीमोग्लोबिन का मुख्य कार्य क्या है?",
         "what is the main function of hemoglobin?",
         "हीमोग्लोबिन फेफड़ों से ऑक्सीजन को शरीर की कोशिकाओं तक पहुँचाता है और कार्बन डाइऑक्साइड वापस लाता है।",
         "DESCRIPTION",
         [("हीमोग्लोबिन लाल रक्त कोशिकाओं में पाया जाने वाला प्रोटीन है जो ऑक्सीजन को बाँधकर शरीर के सभी भागों तक पहुँचाता है और कार्बन डाइऑक्साइड को वापस लाता है। इसमें आयरन होता है।", True),
          ("हीमोग्लोबिन का कम स्तर एनीमिया का संकेत हो सकता है।", True)]),
    # ---- geography ----
    _row("What is the capital of Australia?",
         "What is the capital of Australia?",
         "The capital of Australia is Canberra.",
         "LOCATION",
         [("Canberra is the capital city of Australia, located in the Australian Capital Territory. It is the seat of the federal government.", True),
          ("Sydney is Australia's largest city and a major financial hub.", False),
          ("Melbourne is known for its cultural events and sports.", False)]),
    _row("भारत की राजधानी कौन सी है?",
         "which is the capital of india?",
         "भारत की राजधानी नई दिल्ली है।",
         "LOCATION",
         [("भारत की राजधानी नई दिल्ली है, जो देश के संसद और सरकार का केंद्र है।", True),
          ("मुंबई भारत की वित्तीय राजधानी मानी जाती है।", False)]),
    _row("What is the largest ocean in the world?",
         "What is the largest ocean in the world?",
         "The Pacific Ocean is the largest ocean in the world.",
         "ENTITY",
         [("The Pacific Ocean is the largest and deepest ocean, covering about one-third of the Earth's surface.", True),
          ("The Atlantic Ocean is the second largest ocean.", False),
          ("The Arctic Ocean is the smallest and shallowest.", False)]),
    _row("What is the currency of Japan?",
         "What is the currency of Japan?",
         "The currency of Japan is the yen (JPY).",
         "ENTITY",
         [("The official currency of Japan is the yen, abbreviated JPY, issued by the Bank of Japan.", True),
          ("The yuan is the currency of China.", False)]),
    _row("कौन सी नदी भारत की सबसे लंबी नदी है?",
         "which is the longest river in india?",
         "गंगा भारत की सबसे लंबी नदी है।",
         "ENTITY",
         [("गंगा नदी भारत की सबसे लंबी नदी है, जो लगभग 2,525 किलोमीटर लंबी है और उत्तराखंड से बंगाल की खाड़ी तक बहती है।", True),
          ("यमुना गंगा की प्रमुख सहायक नदी है।", True)]),
    _row("Which desert is the largest hot desert in the world?",
         "Which desert is the largest hot desert in the world?",
         "The Sahara Desert is the largest hot desert in the world.",
         "ENTITY",
         [("The Sahara Desert in North Africa is the largest hot desert, covering over 9 million square kilometres.", True),
          ("The Thar Desert is located in Rajasthan, India.", False)]),
    # ---- history & people ----
    _row("गांधीजी का जन्म कब और कहाँ हुआ था?",
         "when and where was gandhiji born?",
         "महात्मा गांधी का जन्म 2 अक्टूबर 1869 को पोरबंदर, गुजरात में हुआ था।",
         "NUMERIC",
         [("महात्मा गांधी का जन्म 2 अक्टूबर 1869 को पोरबंदर, गुजरात में हुआ था। उन्होंने भारत के स्वतंत्रता संग्राम में अहिंसा और सत्याग्रह का मार्ग अपनाया।", True),
          ("गांधीजी को राष्ट्रपिता के रूप में सम्मानित किया जाता है।", True)]),
    _row("भारत को स्वतंत्रता कब मिली थी?",
         "when did india get independence?",
         "भारत को 15 अगस्त 1947 को ब्रिटिश शासन से स्वतंत्रता मिली थी।",
         "NUMERIC",
         [("भारत को 15 अगस्त 1947 को ब्रिटिश शासन से स्वतंत्रता मिली। इस दिन को स्वतंत्रता दिवस के रूप में मनाया जाता है।", True),
          ("गणतंत्र दिवस 26 जनवरी 1950 को मनाया जाता है जब संविधान लागू हुआ।", True)]),
    _row("Who invented the light bulb?",
         "Who invented the light bulb?",
         "Thomas Edison is widely credited with inventing the practical light bulb in 1879.",
         "ENTITY",
         [("Thomas Edison developed the first practical, long-lasting incandescent light bulb in 1879 and patented it in 1880.", True),
          ("Nikola Tesla pioneered alternating current (AC) electricity.", False)]),
    _row("Who was the first person to walk on the moon?",
         "Who was the first person to walk on the moon?",
         "Neil Armstrong was the first person to walk on the moon on 20 July 1969.",
         "ENTITY",
         [("Neil Armstrong became the first human to walk on the Moon on 20 July 1969 during the Apollo 11 mission, followed by Buzz Aldrin.", True),
          ("The Apollo 11 mission was launched by NASA from Kennedy Space Center.", True)]),
    # ---- tech & computing ----
    _row("What is RAM in a computer?",
         "What is RAM in a computer?",
         "RAM (Random Access Memory) is the short-term memory a computer uses to store data the CPU needs right now.",
         "DESCRIPTION",
         [("Random Access Memory (RAM) is volatile memory that stores data currently being processed by the CPU. It is faster than storage drives and is cleared when the computer powers off.", True),
          ("ROM (Read Only Memory) retains data even when the computer is off.", False)]),
    _row("What is an API?",
         "What is an API?",
         "An API (Application Programming Interface) lets two software programs communicate with each other.",
         "DESCRIPTION",
         [("An Application Programming Interface (API) is a set of rules that allows one software application to request data or services from another application over a network.", True),
          ("REST is a common architectural style for designing APIs using HTTP methods like GET and POST.", True)]),
    _row("कंप्यूटर का जनक किसे कहा जाता है?",
         "who is called the father of the computer?",
         "चार्ल्स बैबेज को आधुनिक कंप्यूटर का जनक कहा जाता है।",
         "ENTITY",
         [("चार्ल्स बैबेज को आधुनिक कंप्यूटर का जनक माना जाता है; उन्होंने 19वीं सदी में एनालिटिकल इंजन का डिज़ाइन बनाया।", True),
          ("पहला प्रोग्रामेबल इलेक्ट्रॉनिक कंप्यूटर ENIAC 1945 में बनाया गया था।", True)]),
    _row("What does SQL stand for?",
         "What does SQL stand for?",
         "SQL stands for Structured Query Language.",
         "ENTITY",
         [("SQL (Structured Query Language) is a standard language for storing, manipulating, and retrieving data in relational databases.", True),
          ("NoSQL databases store data without fixed table schemas.", False)]),
    _row("What is the difference between HTTP and HTTPS?",
         "What is the difference between HTTP and HTTPS?",
         "HTTPS is HTTP with encryption via TLS, making the connection secure.",
         "DESCRIPTION",
         [("HTTPS (HyperText Transfer Protocol Secure) encrypts data exchanged between a browser and a server using TLS, protecting it from eavesdropping, while HTTP sends data in plain text.", True),
          ("Port 443 is the default port for HTTPS, while port 80 is used for HTTP.", True)]),
    _row("What is machine learning?",
         "What is machine learning?",
         "Machine learning is a branch of AI where systems learn patterns from data to make predictions without being explicitly programmed.",
         "DESCRIPTION",
         [("Machine learning is a subset of artificial intelligence in which algorithms learn patterns from training data and improve their predictions over time without explicit instructions for every case.", True),
          ("Deep learning uses multi-layer neural networks to model complex patterns.", True)]),
    _row("What is the difference between a compiler and an interpreter?",
         "What is the difference between a compiler and an interpreter?",
         "A compiler translates the whole program at once into machine code; an interpreter runs code line by line.",
         "DESCRIPTION",
         [("A compiler converts the entire source code into machine code in one pass before execution, producing an executable file. An interpreter executes the source code line by line at runtime.", True),
          ("Python is an interpreted language, while C is typically compiled.", True)]),
    _row("What is a vector database?",
         "What is a vector database?",
         "A vector database stores and searches data by embeddings (numerical vectors) using similarity, enabling fast retrieval for AI applications.",
         "DESCRIPTION",
         [("A vector database indexes high-dimensional embedding vectors and supports similarity search, returning the nearest neighbours of a query vector. This powers retrieval-augmented generation (RAG) and semantic search.", True),
          ("RAG combines retrieval over a knowledge base with an LLM to answer grounded questions.", True)]),
    # ---- health & biology ----
    _row("What is the boiling point of water?",
         "What is the boiling point of water?",
         "Water boils at 100 °C (212 °F) at standard atmospheric pressure.",
         "NUMERIC",
         [("At sea level, pure water boils at 100 °C or 212 °F. The boiling point decreases at higher altitudes because of lower air pressure.", True),
          ("Adding salt to water raises its boiling point slightly.", False)]),
    _row("टाइप 2 मधुमेह में कौन से खाद्य पदार्थों से बचना चाहिए?",
         "what foods should be avoided in type 2 diabetes?",
         "टाइप 2 मधुमेह में शर्करा युक्त पेय, मिठाई और प्रसंस्कृत खाद्य पदार्थों से बचना चाहिए।",
         "DESCRIPTION",
         [("मधुमेह रोगियों को शक्कर युक्त पेय, मिठाई, सफेद ब्रेड और तले हुए खाद्य पदार्थों से बचना चाहिए क्योंकि ये रक्त शर्करा को तेजी से बढ़ाते हैं।", True),
          ("फाइबर युक्त भोजन जैसे सब्जियाँ और साबुत अनाज रक्त शर्करा नियंत्रण में मदद करते हैं।", True)]),
    _row("How many hours of sleep do adults need?",
         "How many hours of sleep do adults need?",
         "Most adults need 7 to 9 hours of sleep per night.",
         "NUMERIC",
         [("Most healthy adults need between 7 and 9 hours of quality sleep per night to function at their best.", True),
          ("Teenagers typically need 8 to 10 hours of sleep.", True)]),
    _row("What is a balanced diet?",
         "What is a balanced diet?",
         "A balanced diet provides the right proportions of carbohydrates, proteins, fats, vitamins, and minerals.",
         "DESCRIPTION",
         [("A balanced diet includes appropriate proportions of carbohydrates, proteins, healthy fats, vitamins, minerals, and water to maintain health and energy.", True),
          ("Fibre from fruits and vegetables supports digestion and heart health.", True)]),
    # ---- animals & nature ----
    _row("भारत का राष्ट्रीय पक्षी कौन सा है?",
         "which is the national bird of india?",
         "भारत का राष्ट्रीय पक्षी मोर है।",
         "ENTITY",
         [("भारत का राष्ट्रीय पक्षी मोर (Peacock) है, जो अपने रंग-बिरंगे पंखों और नृत्य के लिए प्रसिद्ध है।", True),
          ("भारत का राष्ट्रीय पशु बाघ है और राष्ट्रीय फूल कमल है।", True)]),
    _row("How fast can a cheetah run?",
         "How fast can a cheetah run?",
         "A cheetah can run up to about 112 km/h (70 mph) in short bursts.",
         "NUMERIC",
         [("The cheetah is the fastest land animal, capable of sprinting at speeds up to 112 km/h (70 mph) in short bursts covering up to 400 metres.", True),
          ("The peregrine falcon is the fastest animal in a dive, exceeding 300 km/h.", False)]),
    _row("How long do elephants live?",
         "How long do elephants live?",
         "Elephants can live 60 to 70 years in the wild.",
         "NUMERIC",
         [("African and Asian elephants can live 60 to 70 years in the wild; they are among the longest-lived mammals.", True),
          ("Elephants have the longest gestation period of any land mammal, about 22 months.", True)]),
    # ---- general knowledge ----
    _row("हिंदी भाषा किस लिपि में लिखी जाती है?",
         "in which script is the hindi language written?",
         "हिंदी भाषा देवनागरी लिपि में लिखी जाती है।",
         "DESCRIPTION",
         [("हिंदी भाषा देवनागरी लिपि में लिखी जाती है, जिसमें 11 स्वर और 33 व्यंजन होते हैं। यह लिपि बाएँ से दाएँ लिखी जाती है।", True),
          ("देवनागरी में प्रत्येक व्यंजन में स्वाभाविक 'अ' ध्वनि होती है।", True)]),
    _row("How many continents are there in the world?",
         "How many continents are there in the world?",
         "There are seven continents: Asia, Africa, North America, South America, Antarctica, Europe, and Australia.",
         "NUMERIC",
         [("The seven continents are Asia, Africa, North America, South America, Antarctica, Europe, and Australia. Asia is the largest.", True),
          ("Oceans are five: Pacific, Atlantic, Indian, Arctic, and Southern.", True)]),
    _row("What is the smallest country in the world?",
         "What is the smallest country in the world?",
         "Vatican City is the smallest country in the world.",
         "ENTITY",
         [("Vatican City, with an area of about 0.49 square kilometres, is the smallest independent country in the world.", True),
          ("Monaco is the second smallest country.", True)]),
    _row("What is the most spoken language in the world by native speakers?",
         "What is the most spoken language in the world by native speakers?",
         "Mandarin Chinese has the most native speakers in the world.",
         "ENTITY",
         [("Mandarin Chinese has the largest number of native speakers, over 900 million, followed by Spanish and English.", True),
          ("English is the most widely used second language globally.", True)]),
    _row("What does DNA stand for?",
         "What does DNA stand for?",
         "DNA stands for deoxyribonucleic acid, the molecule that carries genetic instructions.",
         "ENTITY",
         [("Deoxyribonucleic acid (DNA) is a double-helix molecule found in cells that stores the genetic instructions for the development and function of living organisms.", True),
          ("RNA, or ribonucleic acid, helps translate DNA instructions into proteins.", True)]),
    _row("कौन सा विटामिन सूर्य के प्रकाश से शरीर को मिलता है?",
         "which vitamin does the body get from sunlight?",
         "विटामिन D सूर्य के प्रकाश से शरीर को मिलता है।",
         "ENTITY",
         [("विटामिन D त्वचा पर सूर्य के प्रकाश पड़ने से शरीर में बनता है और हड्डियों तथा प्रतिरक्षा प्रणाली के लिए आवश्यक है।", True),
          ("विटामिन C फलों और सब्जियों से मिलता है।", False)]),
    _row("What is a solar eclipse?",
         "What is a solar eclipse?",
         "A solar eclipse occurs when the Moon passes between the Sun and Earth, blocking sunlight.",
         "DESCRIPTION",
         [("A solar eclipse happens when the Moon moves between the Sun and the Earth, casting a shadow and partially or fully blocking the Sun's light from reaching Earth.", True),
          ("A lunar eclipse occurs when Earth blocks sunlight from reaching the Moon.", True)]),
    _row("What is the speed of light?",
         "What is the speed of light?",
         "Light travels at about 299,792 km/s (186,282 miles per second) in a vacuum.",
         "NUMERIC",
         [("Light travels at approximately 299,792 kilometres per second in a vacuum — the universal speed limit.", True),
          ("Sound travels at about 343 metres per second in air, far slower than light.", True)]),
    _row("What is the theory of relativity?",
         "What is the theory of relativity?",
         "Einstein's theory of relativity describes how gravity and motion are linked to space and time.",
         "DESCRIPTION",
         [("Albert Einstein's theory of relativity comprises special relativity (E=mc²) and general relativity, which describes gravity as the curvature of spacetime by mass and energy.", True),
          ("The theory revolutionised our understanding of space, time, and gravity.", True)]),
    _row("किस तत्व को सोना का रासायनिक प्रतीक क्या है?",
         "what is the chemical symbol for gold?",
         "सोने का रासायनिक प्रतीक Au है।",
         "ENTITY",
         [("सोने का रासायनिक प्रतीक Au है, जो लैटिन शब्द 'aurum' से आया है। यह एक चमकीला कीमती धातु है।", True),
          ("चाँदी का रासायनिक प्रतीक Ag है।", False)]),
    _row("How does a touchscreen work?",
         "How does a touchscreen work?",
         "A capacitive touchscreen detects the electrical change caused by your finger touching the screen.",
         "DESCRIPTION",
         [("Capacitive touchscreens work by detecting the change in capacitance when a finger, which conducts electricity, touches the screen's glass. This is why they respond to skin but not gloves.", True),
          ("Resistive touchscreens respond to pressure and work with any object, including styluses and gloves.", True)]),
    _row("What is a blockchain?",
         "What is a blockchain?",
         "A blockchain is a distributed, tamper-resistant digital ledger of transactions shared across a network.",
         "DESCRIPTION",
         [("A blockchain is a distributed digital ledger where records, called blocks, are linked cryptographically and maintained by a peer-to-peer network, making them tamper-resistant.", True),
          ("Bitcoin was the first widely adopted cryptocurrency built on blockchain technology.", True)]),
    _row("एक्वेरियम में मछलियों की देखभाल कैसे करें?",
         "how to take care of fish in an aquarium?",
         "मछलियों के लिए साफ पानी, संतुलित आहार और उचित तापमान आवश्यक है।",
         "DESCRIPTION",
         [("एक्वेरियम में मछलियों की देखभाल के लिए पानी नियमित रूप से बदलें, अतिरिक्त भोजन न दें, और पानी का तापमान 24-28 डिग्री सेल्सियस के बीच रखें।", True),
          ("कुछ मछलियाँ सामुदायिक टैंक में रह सकती हैं जबकि कुछ आक्रामक होती हैं।", True)]),
    _row("What is climate change?",
         "What is climate change?",
         "Climate change is the long-term shift in global temperatures and weather patterns, largely driven by human activity.",
         "DESCRIPTION",
         [("Climate change refers to long-term shifts in temperatures and weather patterns. Since the 1800s, human activities, mainly burning fossil fuels, have been the primary driver, increasing greenhouse gas levels.", True),
          ("Renewable energy sources like solar and wind help reduce greenhouse gas emissions.", True)]),
]
