"""Curated corpus — mirrors the MSMARCO-XI row shape exactly.

Each entry is a (query, answer, passages) triple where passages carry a
gold "is_selected" flag, exactly like the dataset rows. Used as the default
demo corpus so the app boots instantly and works offline. Build the real
MSMARCO-XI index with `HHGOA_USE_REAL=1`.
"""
from __future__ import annotations


def _row(query, eng_query, answer, qtype, passages):
    return {
        "query": query,
        "Eng_Query": eng_query,
        "Answer": answer,
        "query_type": qtype,
        "passages": passages,
    }


FALLBACK_CORPUS: list[dict] = [
    # ---- science & space ----
    _row("मेनहट्टन प्रोजेक्ट की सफलता का तात्कालिक प्रभाव क्या था?",
         "what was the immediate impact of the success of the manhattan project?",
         "मेनहट्टन प्रोजेक्ट की सफलता का तात्कालिक प्रभाव द्वितीय विश्व युद्ध का अंत और जापान का आत्मसमर्पण था।",
         "DESCRIPTION",
         [("परमाणु बम के विकास ने जापान के आत्मसमर्पण में तेजी लाई और द्वितीय विश्व युद्ध समाप्त हुआ। हजारों वैज्ञानिकों और इंजीनियरों ने इस परियोजना में एक साथ काम किया।", True),
          ("वैज्ञानिकों के बीच संचार की उपस्थिति ने परियोजना को समय पर पूरा करने में मदद की।", True),
          ("परियोजना के बाद वैज्ञानिक समुदाय में परिणामों पर गहन बहस हुई।", False)]),
    _row("सौरमंडल का सबसे बड़ा ग्रह कौन सा है?",
         "which is the largest planet in the solar system?",
         "सौरमंडल का सबसे बड़ा ग्रह बृहस्पति है।",
         "ENTITY",
         [("बृहस्पति सौरमंडल का सबसे बड़ा ग्रह है, जो अपनी गैसीय बनावट और ग्रेट रेड स्पॉट के लिए जाना जाता है। इसके 95 से अधिक ज्ञात चंद्रमा हैं।", True),
          ("शनि अपने वलयों के लिए प्रसिद्ध है और आकार में दूसरा सबसे बड़ा ग्रह है।", False),
          ("बुध सौरमंडल का सबसे छोटा ग्रह है।", False)]),
    _row("सूर्य का सतही तापमान कितना होता है?",
         "what is the surface temperature of the sun?",
         "सूर्य की सतह का तापमान लगभग 5,500 डिग्री सेल्सियस है।",
         "NUMERIC",
         [("सूर्य की सतह का तापमान लगभग 5,500 °C है, जबकि इसका केंद्र लगभग 15 मिलियन °C पर परमाणु संलयन करता है।", True),
          ("सूर्य से निकलने वाली ऊर्जा परमाणु संलयन से उत्पन्न होती है।", True)]),
    _row("माउंट एवरेस्ट की ऊँचाई कितनी है?",
         "what is the height of mount everest?",
         "माउंट एवरेस्ट की ऊँचाई 8,848.86 मीटर (29,032 फीट) है।",
         "NUMERIC",
         [("माउंट एवरेस्ट विश्व की सबसे ऊँची चोटी है, जिसकी ऊँचाई 8,848.86 मीटर (29,032 फीट) मापी गई है। यह नेपाल और चीन की सीमा पर स्थित है।", True),
          ("एवरेस्ट पर्वतारोहण पहली बार 1953 में एडमंड हिलेरी और तेनजिंग नोर्गे ने किया था।", True)]),
    _row("प्रकाश संश्लेषण क्या है?",
         "what is photosynthesis?",
         "प्रकाश संश्लेषण वह प्रक्रिया है जिसमें पौधे सूर्य के प्रकाश से कार्बन डाइऑक्साइड और पानी का उपयोग करके भोजन बनाते हैं।",
         "DESCRIPTION",
         [("प्रकाश संश्लेषण में पौधे क्लोरोफिल की मदद से सूर्य की ऊर्जा को रासायनिक ऊर्जा में बदलते हैं, कार्बन डाइऑक्साइड और पानी को ग्लूकोज़ और ऑक्सीजन में परिवर्तित करते हैं।", True),
          ("यह प्रक्रिया मुख्य रूप से पत्तियों में स्थित क्लोरोप्लास्ट में होती है।", True)]),
    _row("पानी का रासायनिक सूत्र क्या है?",
         "what is the chemical formula of water?",
         "पानी का रासायनिक सूत्र H2O है।",
         "ENTITY",
         [("पानी का रासायनिक सूत्र H2O है, जिसमें दो हाइड्रोजन परमाणु और एक ऑक्सीजन परमाणु होते हैं।", True),
          ("कार्बन डाइऑक्साइड का रासायनिक सूत्र CO2 है।", False)]),
    _row("ओजोन परत क्यों महत्वपूर्ण है?",
         "why is the ozone layer important?",
         "ओजोन परत सूर्य की हानिकारक पराबैंगनी किरणों से पृथ्वी पर जीवन की रक्षा करती है।",
         "DESCRIPTION",
         [("ओजोन परत समतापमंडल में स्थित है और सूर्य की हानिकारक पराबैंगनी (UV-B) किरणों को अवशोषित कर पृथ्वी पर जीवन की रक्षा करती है।", True),
          ("ओजोन परत के क्षरण के प्रमुख कारण क्लोरोफ्लोरोकार्बन (CFC) गैसें थीं।", True)]),
    _row("हीमोग्लोबिन का मुख्य कार्य क्या है?",
         "what is the main function of hemoglobin?",
         "हीमोग्लोबिन फेफड़ों से ऑक्सीजन को शरीर की कोशिकाओं तक पहुँचाता है और कार्बन डाइऑक्साइड वापस लाता है।",
         "DESCRIPTION",
         [("हीमोग्लोबिन लाल रक्त कोशिकाओं में पाया जाने वाला प्रोटीन है जो ऑक्सीजन को बाँधकर शरीर के सभी भागों तक पहुँचाता है और कार्बन डाइऑक्साइड को वापस लाता है। इसमें आयरन होता है।", True),
          ("हीमोग्लोबिन का कम स्तर एनीमिया का संकेत हो सकता है।", True)]),
    # ---- geography ----
    _row("What is the capital of Australia?",
         "What is the capital of Australia?",
         "The capital of Australia is Canberra.",
         "LOCATION",
         [("Canberra is the capital city of Australia, located in the Australian Capital Territory. It is the seat of the federal government.", True),
          ("Sydney is Australia's largest city and a major financial hub.", False),
          ("Melbourne is known for its cultural events and sports.", False)]),
    _row("भारत की राजधानी कौन सी है?",
         "which is the capital of india?",
         "भारत की राजधानी नई दिल्ली है।",
         "LOCATION",
         [("भारत की राजधानी नई दिल्ली है, जो देश के संसद और सरकार का केंद्र है।", True),
          ("मुंबई भारत की वित्तीय राजधानी मानी जाती है।", False)]),
    _row("भारत का प्रधानमंत्री कौन है?",
         "who is the prime minister of india?",
         "भारत के वर्तमान प्रधानमंत्री नरेंद्र मोदी हैं।",
         "ENTITY",
         [("भारत के वर्तमान प्रधानमंत्री नरेंद्र मोदी हैं, जिन्होंने मई 2014 से यह पद संभाला है।", True),
          ("प्रधानमंत्री भारत सरकार के कार्यकारी प्रमुख होते हैं।", True)]),
    _row("What is the largest ocean in the world?",
         "What is the largest ocean in the world?",
         "The Pacific Ocean is the largest ocean in the world.",
         "ENTITY",
         [("The Pacific Ocean is the largest and deepest ocean, covering about one-third of the Earth's surface.", True),
          ("The Atlantic Ocean is the second largest ocean.", False),
          ("The Arctic Ocean is the smallest and shallowest.", False)]),
    _row("What is the currency of Japan?",
         "What is the currency of Japan?",
         "The currency of Japan is the yen (JPY).",
         "ENTITY",
         [("The official currency of Japan is the yen, abbreviated JPY, issued by the Bank of Japan.", True),
          ("The yuan is the currency of China.", False)]),
    _row("कौन सी नदी भारत की सबसे लंबी नदी है?",
         "which is the longest river in india?",
         "गंगा भारत की सबसे लंबी नदी है।",
         "ENTITY",
         [("गंगा नदी भारत की सबसे लंबी नदी है, जो लगभग 2,525 किलोमीटर लंबी है और उत्तराखंड से बंगाल की खाड़ी तक बहती है।", True),
          ("यमुना गंगा की प्रमुख सहायक नदी है।", True)]),
    _row("Which desert is the largest hot desert in the world?",
         "Which desert is the largest hot desert in the world?",
         "The Sahara Desert is the largest hot desert in the world.",
         "ENTITY",
         [("The Sahara Desert in North Africa is the largest hot desert, covering over 9 million square kilometres.", True),
          ("The Thar Desert is located in Rajasthan, India.", False)]),
    # ---- history & people ----
    _row("गांधीजी का जन्म कब और कहाँ हुआ था?",
         "when and where was gandhiji born?",
         "महात्मा गांधी का जन्म 2 अक्टूबर 1869 को पोरबंदर, गुजरात में हुआ था।",
         "NUMERIC",
         [("महात्मा गांधी का जन्म 2 अक्टूबर 1869 को पोरबंदर, गुजरात में हुआ था। उन्होंने भारत के स्वतंत्रता संग्राम में अहिंसा और सत्याग्रह का मार्ग अपनाया।", True),
          ("गांधीजी को राष्ट्रपिता के रूप में सम्मानित किया जाता है।", True)]),
    _row("भारत को स्वतंत्रता कब मिली थी?",
         "when did india get independence?",
         "भारत को 15 अगस्त 1947 को ब्रिटिश शासन से स्वतंत्रता मिली थी।",
         "NUMERIC",
         [("भारत को 15 अगस्त 1947 को ब्रिटिश शासन से स्वतंत्रता मिली। इस दिन को स्वतंत्रता दिवस के रूप में मनाया जाता है।", True),
          ("गणतंत्र दिवस 26 जनवरी 1950 को मनाया जाता है जब संविधान लागू हुआ।", True)]),
    _row("Who invented the light bulb?",
         "Who invented the light bulb?",
         "Thomas Edison is widely credited with inventing the practical light bulb in 1879.",
         "ENTITY",
         [("Thomas Edison developed the first practical, long-lasting incandescent light bulb in 1879 and patented it in 1880.", True),
          ("Nikola Tesla pioneered alternating current (AC) electricity.", False)]),
    _row("Who was the first person to walk on the moon?",
         "Who was the first person to walk on the moon?",
         "Neil Armstrong was the first person to walk on the moon on 20 July 1969.",
         "ENTITY",
         [("Neil Armstrong became the first human to walk on the Moon on 20 July 1969 during the Apollo 11 mission, followed by Buzz Aldrin.", True),
          ("The Apollo 11 mission was launched by NASA from Kennedy Space Center.", True)]),
    # ---- tech & computing ----
    _row("What is RAM in a computer?",
         "What is RAM in a computer?",
         "RAM (Random Access Memory) is the short-term memory a computer uses to store data the CPU needs right now.",
         "DESCRIPTION",
         [("Random Access Memory (RAM) is volatile memory that stores data currently being processed by the CPU. It is faster than storage drives and is cleared when the computer powers off.", True),
          ("ROM (Read Only Memory) retains data even when the computer is off.", False)]),
    _row("What is an API?",
         "What is an API?",
         "An API (Application Programming Interface) lets two software programs communicate with each other.",
         "DESCRIPTION",
         [("An Application Programming Interface (API) is a set of rules that allows one software application to request data or services from another application over a network.", True),
          ("REST is a common architectural style for designing APIs using HTTP methods like GET and POST.", True)]),
    _row("कंप्यूटर का जनक किसे कहा जाता है?",
         "who is called the father of the computer?",
         "चार्ल्स बैबेज को आधुनिक कंप्यूटर का जनक कहा जाता है।",
         "ENTITY",
         [("चार्ल्स बैबेज को आधुनिक कंप्यूटर का जनक माना जाता है; उन्होंने 19वीं सदी में एनालिटिकल इंजन का डिज़ाइन बनाया।", True),
          ("पहला प्रोग्रामेबल इलेक्ट्रॉनिक कंप्यूटर ENIAC 1945 में बनाया गया था।", True)]),
    _row("What does SQL stand for?",
         "What does SQL stand for?",
         "SQL stands for Structured Query Language.",
         "ENTITY",
         [("SQL (Structured Query Language) is a standard language for storing, manipulating, and retrieving data in relational databases.", True),
          ("NoSQL databases store data without fixed table schemas.", False)]),
    _row("What is the difference between HTTP and HTTPS?",
         "What is the difference between HTTP and HTTPS?",
         "HTTPS is HTTP with encryption via TLS, making the connection secure.",
         "DESCRIPTION",
         [("HTTPS (HyperText Transfer Protocol Secure) encrypts data exchanged between a browser and a server using TLS, protecting it from eavesdropping, while HTTP sends data in plain text.", True),
          ("Port 443 is the default port for HTTPS, while port 80 is used for HTTP.", True)]),
    _row("What is machine learning?",
         "What is machine learning?",
         "Machine learning is a branch of AI where systems learn patterns from data to make predictions without being explicitly programmed.",
         "DESCRIPTION",
         [("Machine learning is a subset of artificial intelligence in which algorithms learn patterns from training data and improve their predictions over time without explicit instructions for every case.", True),
          ("Deep learning uses multi-layer neural networks to model complex patterns.", True)]),
    _row("What is the difference between a compiler and an interpreter?",
         "What is the difference between a compiler and an interpreter?",
         "A compiler translates the whole program at once into machine code; an interpreter runs code line by line.",
         "DESCRIPTION",
         [("A compiler converts the entire source code into machine code in one pass before execution, producing an executable file. An interpreter executes the source code line by line at runtime.", True),
          ("Python is an interpreted language, while C is typically compiled.", True)]),
    _row("What is a vector database?",
         "What is a vector database?",
         "A vector database stores and searches data by embeddings (numerical vectors) using similarity, enabling fast retrieval for AI applications.",
         "DESCRIPTION",
         [("A vector database indexes high-dimensional embedding vectors and supports similarity search, returning the nearest neighbours of a query vector. This powers retrieval-augmented generation (RAG) and semantic search.", True),
          ("RAG combines retrieval over a knowledge base with an LLM to answer grounded questions.", True)]),
    # ---- health & biology ----
    _row("What is the boiling point of water?",
         "What is the boiling point of water?",
         "Water boils at 100 °C (212 °F) at standard atmospheric pressure.",
         "NUMERIC",
         [("At sea level, pure water boils at 100 °C or 212 °F. The boiling point decreases at higher altitudes because of lower air pressure.", True),
          ("Adding salt to water raises its boiling point slightly.", False)]),
    _row("टाइप 2 मधुमेह में कौन से खाद्य पदार्थों से बचना चाहिए?",
         "what foods should be avoided in type 2 diabetes?",
         "टाइप 2 मधुमेह में शर्करा युक्त पेय, मिठाई और प्रसंस्कृत खाद्य पदार्थों से बचना चाहिए।",
         "DESCRIPTION",
         [("मधुमेह रोगियों को शक्कर युक्त पेय, मिठाई, सफेद ब्रेड और तले हुए खाद्य पदार्थों से बचना चाहिए क्योंकि ये रक्त शर्करा को तेजी से बढ़ाते हैं।", True),
          ("फाइबर युक्त भोजन जैसे सब्जियाँ और साबुत अनाज रक्त शर्करा नियंत्रण में मदद करते हैं।", True)]),
    _row("How many hours of sleep do adults need?",
         "How many hours of sleep do adults need?",
         "Most adults need 7 to 9 hours of sleep per night.",
         "NUMERIC",
         [("Most healthy adults need between 7 and 9 hours of quality sleep per night to function at their best.", True),
          ("Teenagers typically need 8 to 10 hours of sleep.", True)]),
    _row("What is a balanced diet?",
         "What is a balanced diet?",
         "A balanced diet provides the right proportions of carbohydrates, proteins, fats, vitamins, and minerals.",
         "DESCRIPTION",
         [("A balanced diet includes appropriate proportions of carbohydrates, proteins, healthy fats, vitamins, minerals, and water to maintain health and energy.", True),
          ("Fibre from fruits and vegetables supports digestion and heart health.", True)]),
    # ---- animals & nature ----
    _row("भारत का राष्ट्रीय पक्षी कौन सा है?",
         "which is the national bird of india?",
         "भारत का राष्ट्रीय पक्षी मोर है।",
         "ENTITY",
         [("भारत का राष्ट्रीय पक्षी मोर (Peacock) है, जो अपने रंग-बिरंगे पंखों और नृत्य के लिए प्रसिद्ध है।", True),
          ("भारत का राष्ट्रीय पशु बाघ है और राष्ट्रीय फूल कमल है।", True)]),
    _row("How fast can a cheetah run?",
         "How fast can a cheetah run?",
         "A cheetah can run up to about 112 km/h (70 mph) in short bursts.",
         "NUMERIC",
         [("The cheetah is the fastest land animal, capable of sprinting at speeds up to 112 km/h (70 mph) in short bursts covering up to 400 metres.", True),
          ("The peregrine falcon is the fastest animal in a dive, exceeding 300 km/h.", False)]),
    _row("How long do elephants live?",
         "How long do elephants live?",
         "Elephants can live 60 to 70 years in the wild.",
         "NUMERIC",
         [("African and Asian elephants can live 60 to 70 years in the wild; they are among the longest-lived mammals.", True),
          ("Elephants have the longest gestation period of any land mammal, about 22 months.", True)]),
    # ---- general knowledge ----
    _row("हिंदी भाषा किस लिपि में लिखी जाती है?",
         "in which script is the hindi language written?",
         "हिंदी भाषा देवनागरी लिपि में लिखी जाती है।",
         "DESCRIPTION",
         [("हिंदी भाषा देवनागरी लिपि में लिखी जाती है, जिसमें 11 स्वर और 33 व्यंजन होते हैं। यह लिपि बाएँ से दाएँ लिखी जाती है।", True),
          ("देवनागरी में प्रत्येक व्यंजन में स्वाभाविक 'अ' ध्वनि होती है।", True)]),
    _row("How many continents are there in the world?",
         "How many continents are there in the world?",
         "There are seven continents: Asia, Africa, North America, South America, Antarctica, Europe, and Australia.",
         "NUMERIC",
         [("The seven continents are Asia, Africa, North America, South America, Antarctica, Europe, and Australia. Asia is the largest.", True),
          ("Oceans are five: Pacific, Atlantic, Indian, Arctic, and Southern.", True)]),
    _row("What is the smallest country in the world?",
         "What is the smallest country in the world?",
         "Vatican City is the smallest country in the world.",
         "ENTITY",
         [("Vatican City, with an area of about 0.49 square kilometres, is the smallest independent country in the world.", True),
          ("Monaco is the second smallest country.", True)]),
    _row("What is the most spoken language in the world by native speakers?",
         "What is the most spoken language in the world by native speakers?",
         "Mandarin Chinese has the most native speakers in the world.",
         "ENTITY",
         [("Mandarin Chinese has the largest number of native speakers, over 900 million, followed by Spanish and English.", True),
          ("English is the most widely used second language globally.", True)]),
    _row("What does DNA stand for?",
         "What does DNA stand for?",
         "DNA stands for deoxyribonucleic acid, the molecule that carries genetic instructions.",
         "ENTITY",
         [("Deoxyribonucleic acid (DNA) is a double-helix molecule found in cells that stores the genetic instructions for the development and function of living organisms.", True),
          ("RNA, or ribonucleic acid, helps translate DNA instructions into proteins.", True)]),
    _row("कौन सा विटामिन सूर्य के प्रकाश से शरीर को मिलता है?",
         "which vitamin does the body get from sunlight?",
         "विटामिन D सूर्य के प्रकाश से शरीर को मिलता है।",
         "ENTITY",
         [("विटामिन D त्वचा पर सूर्य के प्रकाश पड़ने से शरीर में बनता है और हड्डियों तथा प्रतिरक्षा प्रणाली के लिए आवश्यक है।", True),
          ("विटामिन C फलों और सब्जियों से मिलता है।", False)]),
    _row("What is a solar eclipse?",
         "What is a solar eclipse?",
         "A solar eclipse occurs when the Moon passes between the Sun and Earth, blocking sunlight.",
         "DESCRIPTION",
         [("A solar eclipse happens when the Moon moves between the Sun and the Earth, casting a shadow and partially or fully blocking the Sun's light from reaching Earth.", True),
          ("A lunar eclipse occurs when Earth blocks sunlight from reaching the Moon.", True)]),
    _row("What is the speed of light?",
         "What is the speed of light?",
         "Light travels at about 299,792 km/s (186,282 miles per second) in a vacuum.",
         "NUMERIC",
         [("Light travels at approximately 299,792 kilometres per second in a vacuum — the universal speed limit.", True),
          ("Sound travels at about 343 metres per second in air, far slower than light.", True)]),
    _row("What is the theory of relativity?",
         "What is the theory of relativity?",
         "Einstein's theory of relativity describes how gravity and motion are linked to space and time.",
         "DESCRIPTION",
         [("Albert Einstein's theory of relativity comprises special relativity (E=mc²) and general relativity, which describes gravity as the curvature of spacetime by mass and energy.", True),
          ("The theory revolutionised our understanding of space, time, and gravity.", True)]),
    _row("किस तत्व को सोना का रासायनिक प्रतीक क्या है?",
         "what is the chemical symbol for gold?",
         "सोने का रासायनिक प्रतीक Au है।",
         "ENTITY",
         [("सोने का रासायनिक प्रतीक Au है, जो लैटिन शब्द 'aurum' से आया है। यह एक चमकीला कीमती धातु है।", True),
          ("चाँदी का रासायनिक प्रतीक Ag है।", False)]),
    _row("How does a touchscreen work?",
         "How does a touchscreen work?",
         "A capacitive touchscreen detects the electrical change caused by your finger touching the screen.",
         "DESCRIPTION",
         [("Capacitive touchscreens work by detecting the change in capacitance when a finger, which conducts electricity, touches the screen's glass. This is why they respond to skin but not gloves.", True),
          ("Resistive touchscreens respond to pressure and work with any object, including styluses and gloves.", True)]),
    _row("What is a blockchain?",
         "What is a blockchain?",
         "A blockchain is a distributed, tamper-resistant digital ledger of transactions shared across a network.",
         "DESCRIPTION",
         [("A blockchain is a distributed digital ledger where records, called blocks, are linked cryptographically and maintained by a peer-to-peer network, making them tamper-resistant.", True),
          ("Bitcoin was the first widely adopted cryptocurrency built on blockchain technology.", True)]),
    _row("एक्वेरियम में मछलियों की देखभाल कैसे करें?",
         "how to take care of fish in an aquarium?",
         "मछलियों के लिए साफ पानी, संतुलित आहार और उचित तापमान आवश्यक है।",
         "DESCRIPTION",
         [("एक्वेरियम में मछलियों की देखभाल के लिए पानी नियमित रूप से बदलें, अतिरिक्त भोजन न दें, और पानी का तापमान 24-28 डिग्री सेल्सियस के बीच रखें।", True),
          ("कुछ मछलियाँ सामुदायिक टैंक में रह सकती हैं जबकि कुछ आक्रामक होती हैं।", True)]),
    _row("What is climate change?",
         "What is climate change?",
         "Climate change is the long-term shift in global temperatures and weather patterns, largely driven by human activity.",
         "DESCRIPTION",
         [("Climate change refers to long-term shifts in temperatures and weather patterns. Since the 1800s, human activities, mainly burning fossil fuels, have been the primary driver, increasing greenhouse gas levels.", True),
          ("Renewable energy sources like solar and wind help reduce greenhouse gas emissions.", True)]),

    # ---- Goa Tourism & Culture (Multilingual: EN, HI, MR) ----
    _row("what is the best time to visit goa?",
         "what is the best time to visit goa?",
         "The best time to visit Goa is between November and February during the winter months when the weather is pleasant, cool, and perfect for beach activities, water sports, and festivals.",
         "DESCRIPTION",
         [("The ideal time to visit Goa is from mid-November to mid-February when the weather is comfortable and dry.", True),
          ("Monsoon in Goa runs from June to October and is lush green.", False)]),
    _row("गोवा घूमने का सबसे अच्छा समय कौन सा है?",
         "what is the best time to visit goa?",
         "गोवा घूमने का सबसे अच्छा समय नवंबर से फरवरी के बीच होता है, जब मौसम सुहावना, ठंडा और समुद्र तट पर घूमने तथा त्योहारों के लिए सबसे अनुकूल होता है।",
         "DESCRIPTION",
         [("गोवा की यात्रा के लिए नवंबर से फरवरी का समय सबसे अच्छा माना जाता है क्योंकि इस दौरान मौसम सुहावना रहता है।", True)]),
    _row("गोव्यात फिरण्यासाठी सर्वात चांगली वेळ कोणती आहे?",
         "what is the best time to visit goa?",
         "गोव्यात फिरण्यासाठी नोव्हेंबर ते फेब्रुवारी दरम्यानचा काळ सर्वात उत्तम मानला जातो, जेव्हा हवामान अतिशय आल्हाददायक आणि समुद्रकिनाऱ्यांवर फिरण्यासाठी अनुकूल असते.",
         "DESCRIPTION",
         [("गोव्यात फिरण्यासाठी नोव्हेंबर ते फेब्रुवारी हा काळ सर्वोत्तम मानला जातो. या काळात हवामान आल्हाददायक असते.", True)]),

    _row("what are the famous foods and seafood in goa?",
         "what are the famous foods and seafood in goa?",
         "Goa is famous for its Goan fish curry, prawn balchão, pork vindaloo, chicken xacuti, bebinca dessert, and traditional cashew feni drink.",
         "ENTITY",
         [("Goan cuisine features fish curry with rice, vindaloo, xacuti, prawn balchão, bebinca dessert, and local feni drink.", True)]),
    _row("गोवा के प्रसिद्ध भोजन और पेय पदार्थ कौन से हैं?",
         "what are the famous foods and drinks in goa?",
         "गोवा का प्रसिद्ध भोजन गोअन फिश करी, प्रॉन बालचाओ, पोर्क विंदालू, चिकन जाकुती और पारंपरिक मिठाई बेबिका है। यहाँ का प्रसिद्ध स्थानीय पेय काजू फेणी है।",
         "ENTITY",
         [("गोवा का पारंपरिक भोजन फिश करी चावल, विंदालू, बेबिका और काजू फेणी है।", True)]),
    _row("गोव्यातील प्रसिद्ध खाद्यपदार्थ आणि पेये कोणती आहेत?",
         "what are the famous foods and drinks in goa?",
         "गोव्याचे प्रसिद्ध खाद्यपदार्थ म्हणजे गोवन फिश करी राईस, कोळंबी बालचाव, चिकन शाकुती, पोर्क विंदालू आणि प्रसिद्ध पारंपरिक मिठाई बेबिका आहे. तसेच काजू फेणी हे प्रसिद्ध पेय आहे.",
         "ENTITY",
         [("गोव्यात फिश करी राईस, शाकुती, विंदालू, बेबिका आणि काजू फेणी अतिशय प्रसिद्ध आहेत.", True)]),

    _row("what are the top beaches to visit in goa?",
         "what are the top beaches to visit in goa?",
         "Top beaches in North Goa include Baga, Calangute, and Anjuna for nightlife and water sports. South Goa features quieter beaches like Palolem, Colva, and Miramar in Panaji.",
         "ENTITY",
         [("Famous beaches in Goa include Baga, Calangute, Anjuna in the north and Palolem, Colva, and Miramar in the south.", True)]),
    _row("गोवा के सबसे प्रसिद्ध समुद्र तट कौन से हैं?",
         "what are the top beaches in goa?",
         "गोवा के मुख्य समुद्र तटों में उत्तरी गोवा के बागा, कलंगूट, अंजुना (वाटर स्पोर्ट्स और नाइटलाइफ के लिए) और दक्षिण गोवा के पालोलेम, कोलवा और पणजी का मिरामार तट शामिल हैं।",
         "ENTITY",
         [("उत्तरी गोवा में बागा और कलंगूट तथा दक्षिण गोवा में पालोलेम और पणजी का मिरामार प्रसिद्ध समुद्र तट हैं।", True)]),
    _row("गोव्यातील सर्वात प्रसिद्ध समुद्रकिनारे कोणते आहेत?",
         "what are the most famous beaches in goa?",
         "गोव्यातील प्रसिद्ध समुद्रकिनाऱ्यांमध्ये उत्तर गोव्यातील बागा, कलंगूट, अंजुना आणि दक्षिण गोव्यातील पालोलेम, कोलवा व पणजी येथील मिरामार समुद्रकिनारा यांचा समावेश होतो.",
         "ENTITY",
         [("गोव्यातील प्रमुख समुद्रकिनाऱ्यांमध्ये बागा, कलंगूट, अंजुना, पालोलेम आणि मिरामार यांचा समावेश आहे.", True)]),

    _row("what is the official language of goa?",
         "what is the official language of goa?",
         "The official language of Goa is Konkani (in Devanagari script). Marathi, English, and Hindi are also widely spoken and used.",
         "ENTITY",
         [("Konkani is the official language of Goa under the Goa Official Language Act of 1987. Marathi and English are also widely used.", True)]),
    _row("गोवा की राजभाषा कौन सी है?",
         "what is the official language of goa?",
         "गोवा की आधिकारिक राजभाषा कोंकणी (देवनागरी लिपि में) है। इसके अलावा मराठी, हिंदी और अंग्रेजी भी व्यापक रूप से बोली जाती हैं।",
         "ENTITY",
         [("गोवा की राजभाषा कोंकणी है। मराठी और अंग्रेजी भी आधिकारिक और सामान्य कार्यों में उपयोग की जाती हैं।", True)]),
    _row("गोव्याची अधिकृत राजभाषा कोणती आहे?",
         "what is the official language of goa?",
         "गोव्याची अधिकृत राजभाषा 'कोंकणी' (देवनागरी लिपी) आहे. तसेच मराठी, इंग्रजी आणि हिंदी भाषा देखील मोठ्या प्रमाणावर वापरल्या जातात.",
         "ENTITY",
         [("गोव्याची राजभाषा कोंकणी आहे. यासोबतच मराठी आणि इंग्रजी भाषांचा वापर मोठ्या प्रमाणावर केला जातो.", True)]),

    _row("what is dudhsagar falls in goa?",
         "what is dudhsagar falls in goa?",
         "Dudhsagar Falls is a majestic four-tiered waterfall on the Mandovi River located on the Goa-Karnataka border, famous for its milky white cascading waters.",
         "ENTITY",
         [("Dudhsagar Falls is a four-tiered waterfall located on the Mandovi River in Goa, standing at a height of 310 metres.", True)]),
    _row("दूधसागर जलप्रपात कहाँ स्थित है?",
         "where is dudhsagar falls located?",
         "दूधसागर जलप्रपात गोवा-कर्नाटक सीमा पर मंडोवी नदी पर स्थित एक विशाल 4-स्तरीय जलप्रपात है, जिसकी ऊँचाई लगभग 310 मीटर है।",
         "ENTITY",
         [("दूधसागर जलप्रपात गोवा में मंडोवी नदी पर स्थित है और अपने दूध जैसे सफेद गिरते पानी के लिए प्रसिद्ध है।", True)]),
    _row("दूधसागर धबधबा कुठे आहे?",
         "where is dudhsagar waterfall located?",
         "दूधसागर धबधबा गोवा-कर्नाटक सीमेवर मांडवी नदीवर वसलेला एक भव्य ४-टप्प्यांचा धबधबा आहे, ज्याची उंची सुमारे ३१० मीटर आहे.",
         "ENTITY",
         [("दूधसागर धबधबा गोव्यात मांडवी नदीवर स्थित असून तो आपल्या दुधासारख्या पांढऱ्या फेसाळलेल्या पाण्यासाठी ओळखला जातो.", True)]),

    # ---- Rivers & Geography (Multilingual: EN, HI, MR) ----
    _row("What is the largest river in India?",
         "what is the largest river in India?",
         "The Ganges (Ganga) is the largest and longest river in India, flowing over 2,525 kilometres from the Himalayas to the Bay of Bengal.",
         "ENTITY",
         [("The Ganges (Ganga) is the longest and largest river in India, stretching over 2,525 km across India and Bangladesh.", True),
          ("The Godavari is the second longest river in India, often called the Dakshin Ganga.", True),
          ("The Brahmaputra carries the largest volume of water among rivers flowing through India.", True)]),
    _row("भारत की सबसे बड़ी और लंबी नदी कौन सी है?",
         "what is the largest river in india?",
         "भारत की सबसे लंबी और प्रमुख नदी 'गंगा' है, जिसकी कुल लंबाई लगभग 2,525 किलोमीटर है। यह हिमालय के गंगोत्री हिमनद से निकलकर बंगाल की खाड़ी में गिरती है।",
         "ENTITY",
         [("गंगा भारत की सबसे लंबी और पवित्र नदी है, जिसकी लंबाई 2,525 किमी है।", True),
          ("गोदावरी भारत की दूसरी सबसे लंबी नदी है जिसे दक्षिण गंगा भी कहा जाता है।", True)]),
    _row("भारतातील सर्वात मोठी आणि लांब नदी कोणती आहे?",
         "what is the largest river in india?",
         "भारतातील सर्वात मोठी आणि सर्वात लांब नदी 'गंगा' आहे, ज्याची लांबी सुमारे २,५२५ किलोमीटर आहे. ही नदी हिमालयातून उगम पावून बंगालच्या उपसागराला मिळते.",
         "ENTITY",
         [("गंगा ही भारताची सर्वात लांब नदी असून तिची लांबी सुमारे २,५२५ किमी आहे.", True),
          ("गोदावरी ही दक्षिण भारतातील सर्वात मोठी आणि देशातील दुसरी सर्वात लांब नदी आहे.", True)]),

    _row("what are the major rivers in goa?",
         "what are the major rivers in goa?",
         "The two major lifeline rivers of Goa are the Mandovi (Mahadayi) and the Zuari rivers. Other notable rivers include Chapora, Terekhol, and Sal.",
         "ENTITY",
         [("Mandovi and Zuari are the two primary lifeline rivers of Goa, flowing into the Arabian Sea.", True)]),
    _row("गोवा की प्रमुख नदियाँ कौन सी हैं?",
         "what are the major rivers in goa?",
         "गोवा की दो मुख्य जीवनदायिनी नदियाँ 'मंडोवी' (महादयी) और 'जुआरि' हैं। इसके अलावा चापोरा, तेरेखोल और साल नदियाँ भी प्रमुख हैं।",
         "ENTITY",
         [("मंडोवी और जुआरि गोवा की प्रमुख नदियाँ हैं जो अरब सागर में मिलती हैं।", True)]),
    _row("गोव्यातील प्रमुख नद्या कोणत्या आहेत?",
         "what are the major rivers in goa?",
         "गोव्यातील दोन मुख्य जीवनदायिनी नद्या म्हणजे 'मांडवी' (म्हादई) आणि 'जुवारी' नद्या आहेत. याशिवाय शापोरा आणि तेरेखोल या नद्याही महत्त्वाच्या आहेत.",
         "ENTITY",
         [("मांडवी आणि जुवारी या गोव्यातील सर्वात महत्त्वाच्या जीवनवाहिन्या मानल्या जातात.", True)]),
    # ---- additional common queries (for <50ms latency) ----
    _row("महात्मा गांधी",
         "mahatma gandhi",
         "महात्मा गांधी भारत के राष्ट्रपिता थे जिन्होंने अहिंसा के मार्ग पर चलकर भारत को स्वतंत्रता दिलाई।",
         "ENTITY",
         [("मोहनदास करमचंद गांधी (2 अक्टूबर 1869 - 30 जनवरी 1948) जिन्हें महात्मा गांधी कहा जाता है, भारतीय स्वतंत्रता आंदोलन के प्रमुख नेता थे। उन्हें राष्ट्रपिता की उपाधि दी गई।", True)]),
    _row("कोरोना वायरस क्या है?",
         "what is coronavirus?",
         "कोरोना वायरस (COVID-19) एक संक्रामक बीमारी है जो SARS-CoV-2 वायरस से होती है।",
         "DESCRIPTION",
         [("COVID-19 कोरोना वायरस रोग है जो SARS-CoV-2 वायरस के कारण होता है। यह 2019 में शुरू हुआ और विश्वभर में महामारी बन गया।", True)]),
    _row("भारत में कितने राज्य हैं?",
         "how many states are there in india?",
         "भारत में 28 राज्य और 8 केंद्रशासित प्रदेश हैं।",
         "NUMERIC",
         [("भारत में वर्तमान में 28 राज्य और 8 केंद्रशासित प्रदेश हैं। नवीनतम परिवर्तन 2019 में जम्मू-कश्मीर के पुनर्गठन से हुआ।", True)]),
    _row("William Shakespeare ne kya likha?",
         "what did William Shakespeare write?",
         "विलियम शेक्सपियर ने रोमियो और जूलियट, हैमलेट, मैकबेथ जैसे प्रसिद्ध नाटक लिखे।",
         "ENTITY",
         [("विलियम शेक्सपियर (1564-1616) अंग्रेजी साहित्य के सबसे प्रसिद्ध नाटककार और कवि थे। उन्होंने लगभग 37 नाटक और 154 सोनेट लिखे। उनकी प्रमुख रचनाओं में रोमियो और जूलियट, हैमलेट, ओथेलो, मैकबेथ और द मर्चेंट ऑफ वेनिस शामिल हैं।", True)]),
    _row("What is the capital of India?",
         "What is the capital of India?",
         "The capital of India is New Delhi.",
         "LOCATION",
         [("The capital of India is New Delhi, which serves as the seat of the Indian Parliament and the central government. It is located in the National Capital Territory of Delhi.", True),
          ("Mumbai is considered the financial capital of India.", False)]),
    _row("What is population of India?",
         "what is population of india?",
         "The population of India is approximately 1.44 billion.",
         "NUMERIC",
         [("India's total population is approximately 1.44 billion (2024), making it the most populous country in the world, having surpassed China in 2023.", True)]),
    _row("What did William Shakespeare write?",
         "What did William Shakespeare write?",
         "William Shakespeare wrote famous plays like Romeo and Juliet, Hamlet, and Macbeth.",
         "ENTITY",
         [("William Shakespeare (1564-1616) was the most famous English playwright and poet. He wrote approximately 37 plays and 154 sonnets, including Romeo and Juliet, Hamlet, Othello, Macbeth, and The Merchant of Venice.", True)]),
    _row("What is the ozone layer?",
         "What is the ozone layer?",
         "The ozone layer is a region of the Earth's stratosphere that absorbs most of the Sun's ultraviolet radiation.",
         "DESCRIPTION",
         [("The ozone layer is located in the lower portion of the stratosphere and absorbs 97-99% of the Sun's harmful ultraviolet (UV-B) radiation, protecting life on Earth. It is composed mainly of ozone (O3) molecules.", True)]),
    _row("quantum entanglement kya hai?",
         "what is quantum entanglement?",
         "Quantum entanglement ek quantum mechanics ki phenomena hai jismein do particles aapas mein connected hote hain.",
         "DESCRIPTION",
         [("Quantum entanglement is a phenomenon in quantum mechanics where two or more particles become interconnected and the quantum state of each particle cannot be described independently. When one particle is measured, the other instantly reflects the corresponding state.", True)]),
    _row("गोवा में पर्यटन",
         "tourism in goa",
         "गोवा भारत का एक लोकप्रिय पर्यटन स्थल है जो अपने समुद्र तटों, मंदिरों और पुर्तगाली वास्तुकला के लिए प्रसिद्ध है।",
         "DESCRIPTION",
         [("गोवा भारत का सबसे छोटा राज्य है और समुद्र तटों, नाइटलाइफ, चर्चों और पुर्तगाली औपनिवेशिक वास्तुकला के लिए विश्वभर में प्रसिद्ध है। ओल्ड गोवा के चर्च UNESCO विश्व धरोहर स्थल हैं।", True)]),
    _row("गोवा के मुख्यमंत्री कौन हैं?",
         "who is the chief minister of goa?",
         "गोवा के वर्तमान मुख्यमंत्री प्रमोद सावंत हैं।",
         "ENTITY",
         [("प्रमोद सावंत गोवा के वर्तमान मुख्यमंत्री हैं जो भारतीय जनता पार्टी के सदस्य हैं।", True)]),
]

